stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHA

default:
  tags:
    - runner-tag  

build:
  stage: build
  script:
    - docker build -t sinafathi/mediasoup:$IMAGE_TAG .

test:
  stage: test
  image: node:22
  script:
    - cd server
    - npm ci --omit=dev
    - cd ../app
    - npm ci --legacy-peer-deps
    - npm run lint || true 
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - sed -i "s|sinafathi/mediasoup-demo:v1|$IMAGE_TAG|g" k8s/deployment.yaml
    - kubectl apply -f k8s/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
