apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediasoup-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediasoup-demo
  template:
    metadata:
      labels:
        app: mediasoup-demo
    spec:
      containers:
      - name: mediasoup-demo
        image: sinafathi/mediasoup-demo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4443
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

